/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: WKAC (https://sketchfab.com/WKAC)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/transformers-war-for-cybetron-barricade-b7a7056e4e4646e1a145987b0a4bafa5
Title: Transformers: War For Cybetron Barricade
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useMotionValue, useSpring } from "motion/react";

export function Animation(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/transformers_war_for_cybetron_barricade.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{if(animations.length > 0){actions[animations[0].name]?.play()}},[actions,animations])
   
   const finalY = props.position?.[1] ?? -1;

// start above, so it can "fall"
const yPosition = useMotionValue(finalY + 3);

// spring follows yPosition smoothly
const ySpring = useSpring(yPosition, { stiffness: 120, damping: 20 });

useEffect(() => {
  // trigger the fall on mount (next frame)
  requestAnimationFrame(() => {
    yPosition.set(finalY); // ✅ animate toward finalY
  });
}, [finalY, yPosition]);

useFrame(() => {
  if (!group.current) return;
  group.current.position.y = ySpring.get();
});

  return (
    <group ref={group} {...props} dispose={null}
           rotation={[Math.PI / 2, 0, 0]}
            scale={props.scale || 0.01}
            position={props.position || [1.3, -1, 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="64fb187ec05e4b2f925bddd956e80babfbx"
            >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="RB_BarricadeWeaponArm_SKEL"
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={1}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_106"
                      geometry={nodes.Object_106.geometry}
                      material={materials.RB_Barricade_Mat_INST}
                      skeleton={nodes.Object_106.skeleton}
                    />
                    <skinnedMesh
                      name="Object_107"
                      geometry={nodes.Object_107.geometry}
                      material={materials.MaterialInstanceConstant_679}
                      skeleton={nodes.Object_107.skeleton}
                    />
                    <group
                      name="Object_105"
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                      scale={100}
                    />
                  </group>
                </group>
                <group
                  name="RB_Barricade_SKEL001"
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={100}
                />
                <group
                  name="VH_Barricade_SKEL"
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={1}>
                  <group name="Object_110">
                    <primitive object={nodes._rootJoint_1} />
                    <skinnedMesh
                      name="Object_196"
                      geometry={nodes.Object_196.geometry}
                      material={materials.MaterialInstanceConstant_679}
                      skeleton={nodes.Object_196.skeleton}
                    />
                    <skinnedMesh
                      name="Object_197"
                      geometry={nodes.Object_197.geometry}
                      material={materials.VH_Barricade_NormSpec_Cust_B_Mat_INST}
                      skeleton={nodes.Object_197.skeleton}
                    />
                    <group
                      name="Object_195"
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                      scale={100}
                    />
                  </group>
                </group>
                <group
                  name="VH_Barricade_SKEL001"
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={1}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/transformers_war_for_cybetron_barricade.glb')
